# Generated by Django 5.2.4 on 2025-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='input_data',
            field=models.ImageField(blank=True, null=True, upload_to='input_data/'),
        ),
    ]
