# Generated by Django 5.2.4 on 2025-07-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_job_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_data',
            field=models.ImageField(blank=True, null=True, upload_to='output_data/'),
        ),
    ]
